import user_avatar from "../assets/images/user_avatar.svg";

export const ChatListConst = [
  {
    id: 1,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 2,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 3,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 4,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 5,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 6,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 7,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 8,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 9,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 10,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 11,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 12,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 13,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 14,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 15,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 16,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  },
  {
    id: 17,
    user_avatar: user_avatar,
    user_name: "Имя Фамилия",
    user_price: "От 220 ₽",
    user_stars: "4.5",
    user_reviews: "5 отзывов",
    user_location: "Расстояние между вами 3 км",
    last_message: "Последнее сообщение, последнее...",
  }
];
